### ISSUE TITLE
Node Output Disappears

### ISSUE THREAD

**Issue by ryancasler** [bartbutenaers/node-red-contrib-button-events#3]
Whenever I deploy the node, if I go in to set the timings for the event to be different than the default the output of the node disappears immediately.

**Comment by bartbutenaers** [comment]
Hi @ryancasler,
Sorry for the delay!  Somehow I have completely overlooked your issue...

Do you mean that the node output is gone in the flow editor?
![image](https://user-images.githubusercontent.com/14224149/181959510-77ecb4d9-ad61-40d6-8757-d816ec0ff7cc.png)

I have tried to reproduce it, but it works fine for me.  Could you please describe step by step what you do?

And is there any error in the Node-RED log, or in your browser log?

Thanks!
Bart

**Comment by ryancasler** [comment]
I did not see that you have to add the events that you want yourself.  I thought it just had the default outputs.  

But now i have a new problem.  I am not seeing the triple and quad events from the list in Node Red.  the version that is in NPM is 1.0.1 and it's about a year old.  
![image](https://user-images.githubusercontent.com/30270489/182009950-ca44301e-7a75-4c3c-add7-13b6c20af023.png)

**Comment by bartbutenaers** [comment]
@ryancasler,
I have added a warning on the readme page, about the need to specify the events on the config screen yourself.  Hopefully it is now less confusing...

About the triple and quad events: as you can see in this repository, I have only pushed that new feature to the master branch yesterday.  As soon as @tsknightstorm has found some time to test it, we will announce a beta on Discourse because we need feedback from the community about the new calibration feature.  And only after that we publish it on npm...

**Comment by ryancasler** [comment]
Ah...okay.  No, I didn't notice the date on that until you mentioned it.  Thanks!
